#!/bin/bash



mkdir human_data
cd human_data

#download human transcriptome
wget -q ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_36/gencode.v36.transcripts.fa.gz

#download covid seq
wget -q ftp://ftp.ensemblgenomes.org/pub/viruses/fasta/sars_cov_2/cdna/Sars_cov_2.ASM985889v3.cdna.all.fa.gz

#download GRCh38.d1.vd1.fa.tar.gz and gather EB genes(EB.fasta)

gunzip *.gz
tar -xvf GRCh38.d1.vd1.fa.tar


#create decoy list
grep ">" GRCh38.d1.vd1.fa | cut -d " " -f 1 | tr -d ">" > decoys.txt
        

#combine transcriptomes and decoy fasta files. Can also add viral decoys, spike-ins as decoys.   
cat gencode.v36.transcripts.fa Sars_cov_2.ASM985889v3.cdna.all.fa EB.fasta GRCh38.d1.vd1.fa > human_sars_tr_EB_decoy.fasta


#cleanup
rm gencode.v36.transcripts.fa Sars_cov_2.ASM985889v3.cdna.all.fa EB.fasta GRCh38.d1.vd1.fa  GRCh38.d1.vd1.fa.tar


#create salmon index
time salmon index -t human_sars_tr_EB_decoy.fasta -d decoys.txt -p 15 -i salmon_index

